---
# Source: opa-notary-connector/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-notary-connector
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: opa-notary-connector/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: opa-notary-connector-certs
type: Opaque
data:
  cert.pem: 
  key.pem:
---
# Source: opa-notary-connector/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-notary-connector-config
data:
  trust.yaml: |-
    repositories:
    #- name: 'registry.*'
      #namespace: ".*"
      #trust:
        #enabled: true
        #trustServer: "https://notary-server:4443"
        #signers:
          #- role: "targets"
            #publicKey: ""
---
# Source: opa-notary-connector/templates/webhook-creation.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-notary-connectors
  labels:
data:
  webhooks.yaml: |-
    apiVersion: admissionregistration.k8s.io/v1beta1
    kind: MutatingWebhookConfiguration
    metadata:
      name: notary-admission-config
      labels:
        app.kubernetes.io/name: opa-notary-connector
        helm.sh/chart: opa-notary-connector-0.1.0
        app.kubernetes.io/instance: opa-notary-connector
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/managed-by: Helm
    webhooks:
      - name: trust.hooks.securityenforcement.admission.sighup.io
        clientConfig:
          service:
            name: opa-notary-connector
            namespace: webhook
            path: "/admit"
          caBundle: 
        rules:
          - operations: [ "CREATE", "UPDATE" ]
            apiGroups: ["*"]
            apiVersions: ["*"]
            resources: ["pods", "deployments", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "jobs", "cronjobs"]
        failurePolicy: Fail
---
# Source: opa-notary-connector/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opa-notary-connector
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get"]
---
# Source: opa-notary-connector/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: opa-notary-connector
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opa-notary-connector
subjects:
  - kind: ServiceAccount
    name: opa-notary-connector
    namespace: webhook
---
# Source: opa-notary-connector/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opa-notary-connector
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: opa-notary-connector
    app.kubernetes.io/instance: opa-notary-connector
---
# Source: opa-notary-connector/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-notary-connector
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opa-notary-connector
      app.kubernetes.io/instance: opa-notary-connector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opa-notary-connector
        app.kubernetes.io/instance: opa-notary-connector
    spec:
      volumes:
        - name: config
          configMap:
            name: opa-notary-connector-config
        - name: certs
          secret:
            secretName: opa-notary-connector-certs
      containers:
        - name: opa-notary-connector
          image: "opa-notary-connector:latest"
          command:
            - /opa-notary-connector
            - -c
            - /etc/opa-notary-connector/conf/trust.yaml
            - -v
            - info
            - -l
            - :8443
          imagePullPolicy: IfNotPresent
          env:
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: config
              mountPath: "/etc/opa-notary-connector/conf"
              readOnly: true
            - name: certs
              mountPath: "/etc/opa-notary-connector/tls"
              readOnly: true
          ports:
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTPS
              port: https
          readinessProbe:
            httpGet:
              path: /health
              scheme: HTTPS
              port: https
          resources:
            {}
---
# Source: opa-notary-connector/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "opa-notary-connector-test-connection"
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['opa-notary-connector:443']
  restartPolicy: Never
---
# Source: opa-notary-connector/templates/webhook-creation.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: create-admission-webhooks
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name: create-admission-webhooks
      labels:
        app.kubernetes.io/name: opa-notary-connector
        helm.sh/chart: opa-notary-connector-0.1.0
        app.kubernetes.io/instance: opa-notary-connector
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: opa-notary-connector
      containers:
        - name: kubectl
          image: "quay.io/sighup/kubectl:v1.14.6"
          command:
            - kubectl
            - apply
            - -f
            - /tmp/opa-notary-connector/webhooks.yaml
          volumeMounts:
            - mountPath: "/tmp/opa-notary-connector"
              name: tmp-configmap
      volumes:
        - name: tmp-configmap
          configMap:
            name: opa-notary-connectors
      restartPolicy: OnFailure
---
# Source: opa-notary-connector/templates/webhook-creation.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-admission-webhooks
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/name: opa-notary-connector
    helm.sh/chart: opa-notary-connector-0.1.0
    app.kubernetes.io/instance: opa-notary-connector
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name: -admission-webhooks
      labels:
        app.kubernetes.io/name: opa-notary-connector
        helm.sh/chart: opa-notary-connector-0.1.0
        app.kubernetes.io/instance: opa-notary-connector
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: opa-notary-connector
      containers:
        - name: kubectl
          image: "quay.io/sighup/kubectl:v1.14.6"
          command:
            - kubectl
            - delete
            - -f
            - /tmp/opa-notary-connector/webhooks.yaml
            - --ignore-not-found=true
          volumeMounts:
            - mountPath: "/tmp/opa-notary-connector"
              name: tmp-configmap
      volumes:
        - name: tmp-configmap
          configMap:
            name: opa-notary-connectors
      restartPolicy: OnFailure
