apiVersion: v2
name: opa-notary-connector
description: OPA Notary Connector helm chart
type: application
version: 0.1.0-rc3
appVersion: 0.1.0-rc3

dependencies:
  - name: opa
    version: 1.14.1
    repository: https://kubernetes-charts.storage.googleapis.com
