apiVersion: v2
name: opa-notary-connector
description: OPA Notary Connector helm chart
type: application
version: 0.1.1
appVersion: 0.1.1

dependencies:
  - name: opa
    version: 1.14.6
    repository: "file://../dependency_chart/opa"
